name       : python-hatch-vcs
version    : 0.3.0
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/h/hatch_vcs/hatch_vcs-0.3.0.tar.gz : cec5107cfce482c67f8bc96f18bbc320c9aa0d068180e14ad317bbee5a153fee
homepage   : https://github.com/ofek/hatch-vcs
license    : MIT
component  : programming.python
summary    : Hatch plugin for versioning with your preferred VCS
description: |
    This provides a plugin for Hatch that uses your preferred version control system (like Git) to determine project versions.
builddeps  :
    - git                   # check
    - python-build
    - python-hatchling
    - python-installer
    - python-pytest
    - python-setuptools-scm # check
rundeps    :
    - python-hatchling
    - python-setuptools-scm
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
