name       : python-hatch-vcs
version    : 0.2.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/h/hatch_vcs/hatch_vcs-0.2.0.tar.gz : 9913d733b34eec9bb0345d0626ca32165a4ad2de15d1ce643c36d09ca908abff
homepage   : https://github.com/ofek/hatch-vcs
license    : MIT
component  : programming.python
summary    : Hatch plugin for versioning with your preferred VCS
description: |
    This provides a plugin for Hatch that uses your preferred version control system (like Git) to determine project versions.
builddeps  :
    - git                   # check
    - python-build
    - python-hatchling
    - python-installer
    - python-pytest
    - python-setuptools-scm # check
rundeps    :
    - python-hatchling
    - python-setuptools-scm
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
